#!/bin/bash

python run_mnist.py --model mom_sgd --agg cm --bucketing 2 --attack ALIE --lr 0.01 --seed 123 -b 128 --test-batch-size 2048 -e 20 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.55 --clip-update --clip-mult 0.1 --shuffle
python run_mnist.py --model mom_sgd --agg cm --bucketing 2 --attack ALIE --lr 0.01 --seed 123 -b 128 --test-batch-size 2048 -e 20 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.55 --clip-update --clip-mult 1.0 --shuffle
python run_mnist.py --model mom_sgd --agg cm --bucketing 2 --attack ALIE --lr 0.01 --seed 123 -b 128 --test-batch-size 2048 -e 20 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.55 --clip-update --clip-mult 10.0 --shuffle
python run_mnist.py --model mom_sgd --agg cm --bucketing 2 --attack ALIE --lr 0.01 --seed 123 -b 128 --test-batch-size 2048 -e 20 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.55 --shuffle
python run_mnist.py --model mom_sgd --agg cm --bucketing 2 --attack ALIE --lr 0.001 --seed 123 -b 128 --test-batch-size 2048 -e 20 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.55 --clip-update --clip-mult 0.1 --shuffle
python run_mnist.py --model mom_sgd --agg cm --bucketing 2 --attack ALIE --lr 0.001 --seed 123 -b 128 --test-batch-size 2048 -e 20 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.55 --clip-update --clip-mult 1.0 --shuffle
python run_mnist.py --model mom_sgd --agg cm --bucketing 2 --attack ALIE --lr 0.001 --seed 123 -b 128 --test-batch-size 2048 -e 20 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.55 --clip-update --clip-mult 10.0 --shuffle
python run_mnist.py --model mom_sgd --agg cm --bucketing 2 --attack ALIE --lr 0.001 --seed 123 -b 128 --test-batch-size 2048 -e 20 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.55 --shuffle
