# With Clipping
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 0.1 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 1. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 10. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 100. --shuffle

python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 0.1 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 1. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 10. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 100. --shuffle

python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 0.1 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 1. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 10. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 100. --shuffle

python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 0.1 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 1. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 10. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 100. --shuffle

python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 0.1 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 1. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 10. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 100. --shuffle

python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 0.1 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 1. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 10. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 100. --shuffle

python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 0.1 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 1. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 10. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 100. --shuffle

python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 0.1 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 1. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 10. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 100. --shuffle

python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 0.1 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 1. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 10. --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --clip-update --clip-mult 100. --shuffle

# Without Clipping
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 123 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --shuffle

python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 124 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --shuffle

python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.01 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.001 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --shuffle
python run_cifar.py --model mom_sgd --agg rfa --bucketing 2 --attack SHB --lr 0.0001 --seed 125 -b 32 --test-batch-size 128 -e 30 -n 20 -f 5 --use-cuda --eval-every 1 --compression none --partial-participation --partial-participation-ratio 0.05 --shuffle